// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity_list.proto

package grpcdomain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DumpIdentityListRequest contains nothing
type DumpIdentityListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpIdentityListRequest) Reset()         { *m = DumpIdentityListRequest{} }
func (m *DumpIdentityListRequest) String() string { return proto.CompactTextString(m) }
func (*DumpIdentityListRequest) ProtoMessage()    {}
func (*DumpIdentityListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f8933480fd87ceb, []int{0}
}

func (m *DumpIdentityListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpIdentityListRequest.Unmarshal(m, b)
}
func (m *DumpIdentityListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpIdentityListRequest.Marshal(b, m, deterministic)
}
func (m *DumpIdentityListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpIdentityListRequest.Merge(m, src)
}
func (m *DumpIdentityListRequest) XXX_Size() int {
	return xxx_messageInfo_DumpIdentityListRequest.Size(m)
}
func (m *DumpIdentityListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpIdentityListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpIdentityListRequest proto.InternalMessageInfo

// IdentityListRequest contains the client's & peers' identities
type IdentityListRequest struct {
	// Identity is the identity of the client
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// IdentityList is a list of all domains known to the client
	IdentityList         []*Identity `protobuf:"bytes,2,rep,name=IdentityList,proto3" json:"IdentityList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdentityListRequest) Reset()         { *m = IdentityListRequest{} }
func (m *IdentityListRequest) String() string { return proto.CompactTextString(m) }
func (*IdentityListRequest) ProtoMessage()    {}
func (*IdentityListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f8933480fd87ceb, []int{1}
}

func (m *IdentityListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityListRequest.Unmarshal(m, b)
}
func (m *IdentityListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityListRequest.Marshal(b, m, deterministic)
}
func (m *IdentityListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityListRequest.Merge(m, src)
}
func (m *IdentityListRequest) XXX_Size() int {
	return xxx_messageInfo_IdentityListRequest.Size(m)
}
func (m *IdentityListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityListRequest proto.InternalMessageInfo

func (m *IdentityListRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *IdentityListRequest) GetIdentityList() []*Identity {
	if m != nil {
		return m.IdentityList
	}
	return nil
}

// IdentityListReply contains the server's & peers' identities
type IdentityListReply struct {
	// Identity is the identity of the server
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// IdentityList is a list of all domains known to the server
	IdentityList         []*Identity `protobuf:"bytes,2,rep,name=IdentityList,proto3" json:"IdentityList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdentityListReply) Reset()         { *m = IdentityListReply{} }
func (m *IdentityListReply) String() string { return proto.CompactTextString(m) }
func (*IdentityListReply) ProtoMessage()    {}
func (*IdentityListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f8933480fd87ceb, []int{2}
}

func (m *IdentityListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityListReply.Unmarshal(m, b)
}
func (m *IdentityListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityListReply.Marshal(b, m, deterministic)
}
func (m *IdentityListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityListReply.Merge(m, src)
}
func (m *IdentityListReply) XXX_Size() int {
	return xxx_messageInfo_IdentityListReply.Size(m)
}
func (m *IdentityListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityListReply.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityListReply proto.InternalMessageInfo

func (m *IdentityListReply) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *IdentityListReply) GetIdentityList() []*Identity {
	if m != nil {
		return m.IdentityList
	}
	return nil
}

func init() {
	proto.RegisterType((*DumpIdentityListRequest)(nil), "grpcdomain.DumpIdentityListRequest")
	proto.RegisterType((*IdentityListRequest)(nil), "grpcdomain.IdentityListRequest")
	proto.RegisterType((*IdentityListReply)(nil), "grpcdomain.IdentityListReply")
}

func init() { proto.RegisterFile("identity_list.proto", fileDescriptor_7f8933480fd87ceb) }

var fileDescriptor_7f8933480fd87ceb = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x4c, 0x49, 0xcd,
	0x2b, 0xc9, 0x2c, 0xa9, 0x8c, 0xcf, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0x2f, 0x2a, 0x48, 0x4e, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x93, 0xe2, 0xcd, 0x4f, 0xca,
	0x4a, 0x4d, 0x2e, 0x29, 0x86, 0x48, 0x29, 0x49, 0x72, 0x89, 0xbb, 0x94, 0xe6, 0x16, 0x78, 0x42,
	0x75, 0xf9, 0x64, 0x16, 0x97, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x35, 0x32, 0x72,
	0x09, 0x63, 0x11, 0x17, 0x32, 0xe0, 0xe2, 0x80, 0x09, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b,
	0x89, 0xe8, 0x21, 0x2c, 0xd0, 0x83, 0xc9, 0x05, 0xc1, 0x55, 0x09, 0x59, 0x70, 0xf1, 0x20, 0x1b,
	0x24, 0xc1, 0xa4, 0xc0, 0x8c, 0x53, 0x17, 0x8a, 0x4a, 0xa5, 0x7a, 0x2e, 0x41, 0x54, 0x27, 0x14,
	0xe4, 0x54, 0xd2, 0xd3, 0x01, 0x49, 0x6c, 0xe0, 0x60, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x94, 0xd1, 0xd7, 0x58, 0x58, 0x01, 0x00, 0x00,
}
