// Code generated by protoc-gen-go. DO NOT EDIT.
// source: close_position.proto

package grpcdomain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ClosePositionRequest contains the name of the election which was being held,
type ClosePositionRequest struct {
	// Identity is the identity of the client
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// Name is the name of the service which is open
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// Elected is the port which the service is availible at
	Elected              bool     `protobuf:"varint,3,opt,name=Elected,proto3" json:"Elected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosePositionRequest) Reset()         { *m = ClosePositionRequest{} }
func (m *ClosePositionRequest) String() string { return proto.CompactTextString(m) }
func (*ClosePositionRequest) ProtoMessage()    {}
func (*ClosePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d47d7c531357be, []int{0}
}

func (m *ClosePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosePositionRequest.Unmarshal(m, b)
}
func (m *ClosePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosePositionRequest.Marshal(b, m, deterministic)
}
func (m *ClosePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosePositionRequest.Merge(m, src)
}
func (m *ClosePositionRequest) XXX_Size() int {
	return xxx_messageInfo_ClosePositionRequest.Size(m)
}
func (m *ClosePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClosePositionRequest proto.InternalMessageInfo

func (m *ClosePositionRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *ClosePositionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClosePositionRequest) GetElected() bool {
	if m != nil {
		return m.Elected
	}
	return false
}

// ClosePositionReply contains the acceptance of the Server
type ClosePositionReply struct {
	// Accept is the servers acceptance of the position
	Accept               bool     `protobuf:"varint,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClosePositionReply) Reset()         { *m = ClosePositionReply{} }
func (m *ClosePositionReply) String() string { return proto.CompactTextString(m) }
func (*ClosePositionReply) ProtoMessage()    {}
func (*ClosePositionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_28d47d7c531357be, []int{1}
}

func (m *ClosePositionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClosePositionReply.Unmarshal(m, b)
}
func (m *ClosePositionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClosePositionReply.Marshal(b, m, deterministic)
}
func (m *ClosePositionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClosePositionReply.Merge(m, src)
}
func (m *ClosePositionReply) XXX_Size() int {
	return xxx_messageInfo_ClosePositionReply.Size(m)
}
func (m *ClosePositionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ClosePositionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ClosePositionReply proto.InternalMessageInfo

func (m *ClosePositionReply) GetAccept() bool {
	if m != nil {
		return m.Accept
	}
	return false
}

func init() {
	proto.RegisterType((*ClosePositionRequest)(nil), "grpcdomain.ClosePositionRequest")
	proto.RegisterType((*ClosePositionReply)(nil), "grpcdomain.ClosePositionReply")
}

func init() { proto.RegisterFile("close_position.proto", fileDescriptor_28d47d7c531357be) }

var fileDescriptor_28d47d7c531357be = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xc9, 0x2f,
	0x4e, 0x8d, 0x2f, 0xc8, 0x2f, 0xce, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x4a, 0x2f, 0x2a, 0x48, 0x4e, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x93, 0xe2, 0xcd, 0x4f,
	0xca, 0x4a, 0x4d, 0x2e, 0x29, 0x86, 0x48, 0x29, 0x95, 0x71, 0x89, 0x38, 0x83, 0xb4, 0x04, 0x40,
	0x75, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x19, 0x70, 0x71, 0x78, 0xa6, 0xa4, 0xe6,
	0x95, 0x64, 0x96, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x21, 0x4c, 0xd1,
	0x83, 0xc9, 0x05, 0xc1, 0x55, 0x09, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x12, 0x5c, 0xec, 0xae, 0x39, 0xa9, 0xc9, 0x25, 0xa9,
	0x29, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x30, 0xae, 0x92, 0x0e, 0x97, 0x10, 0x9a, 0xbd,
	0x05, 0x39, 0x95, 0x42, 0x62, 0x5c, 0x6c, 0x8e, 0xc9, 0xc9, 0xa9, 0x05, 0x25, 0x60, 0x3b, 0x39,
	0x82, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x63, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x41,
	0x54, 0xcc, 0xdf, 0x00, 0x00, 0x00,
}
