// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package grpcd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// DominionIdentity represents a dominion
type DominionIdentity struct {
	// Address is the network address of the dominion
	Address *Address `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	// Version is the version of code being run by the dominion
	Version              string   `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DominionIdentity) Reset()         { *m = DominionIdentity{} }
func (m *DominionIdentity) String() string { return proto.CompactTextString(m) }
func (*DominionIdentity) ProtoMessage()    {}
func (*DominionIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *DominionIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DominionIdentity.Unmarshal(m, b)
}
func (m *DominionIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DominionIdentity.Marshal(b, m, deterministic)
}
func (m *DominionIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DominionIdentity.Merge(m, src)
}
func (m *DominionIdentity) XXX_Size() int {
	return xxx_messageInfo_DominionIdentity.Size(m)
}
func (m *DominionIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_DominionIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_DominionIdentity proto.InternalMessageInfo

func (m *DominionIdentity) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DominionIdentity) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// DomainIdentity represents a domain
type DomainIdentity struct {
	// Address is the network address of the domain
	Address *Address `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	// Version is the version of code being run by the domain
	Version string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	// UUID is a Unique Identifier for the domain
	UUID string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Traits is the list of traits of the domain
	Traits []string `protobuf:"bytes,4,rep,name=Traits,proto3" json:"Traits,omitempty"`
	// Services is the list of services an Identity currently offers
	Services             map[string]*ServiceIdentity `protobuf:"bytes,5,rep,name=Services,proto3" json:"Services,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DomainIdentity) Reset()         { *m = DomainIdentity{} }
func (m *DomainIdentity) String() string { return proto.CompactTextString(m) }
func (*DomainIdentity) ProtoMessage()    {}
func (*DomainIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *DomainIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainIdentity.Unmarshal(m, b)
}
func (m *DomainIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainIdentity.Marshal(b, m, deterministic)
}
func (m *DomainIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainIdentity.Merge(m, src)
}
func (m *DomainIdentity) XXX_Size() int {
	return xxx_messageInfo_DomainIdentity.Size(m)
}
func (m *DomainIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_DomainIdentity proto.InternalMessageInfo

func (m *DomainIdentity) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *DomainIdentity) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DomainIdentity) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DomainIdentity) GetTraits() []string {
	if m != nil {
		return m.Traits
	}
	return nil
}

func (m *DomainIdentity) GetServices() map[string]*ServiceIdentity {
	if m != nil {
		return m.Services
	}
	return nil
}

// Service represents a service running under a domain
type ServiceIdentity struct {
	// Type is the type of the service
	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// Address is the network address of the service
	Address              *Address `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIdentity) Reset()         { *m = ServiceIdentity{} }
func (m *ServiceIdentity) String() string { return proto.CompactTextString(m) }
func (*ServiceIdentity) ProtoMessage()    {}
func (*ServiceIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{2}
}

func (m *ServiceIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIdentity.Unmarshal(m, b)
}
func (m *ServiceIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIdentity.Marshal(b, m, deterministic)
}
func (m *ServiceIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIdentity.Merge(m, src)
}
func (m *ServiceIdentity) XXX_Size() int {
	return xxx_messageInfo_ServiceIdentity.Size(m)
}
func (m *ServiceIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIdentity proto.InternalMessageInfo

func (m *ServiceIdentity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ServiceIdentity) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	// IP is the IP address which the domain was last known to communicate over
	IP []byte `protobuf:"bytes,5,opt,name=IP,proto3" json:"IP,omitempty"`
	// Port is the port which the domain was last known to belong communicate over
	Port                 int32    `protobuf:"varint,6,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *Address) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*DominionIdentity)(nil), "grpcd.DominionIdentity")
	proto.RegisterType((*DomainIdentity)(nil), "grpcd.DomainIdentity")
	proto.RegisterMapType((map[string]*ServiceIdentity)(nil), "grpcd.DomainIdentity.ServicesEntry")
	proto.RegisterType((*ServiceIdentity)(nil), "grpcd.ServiceIdentity")
	proto.RegisterType((*Address)(nil), "grpcd.Address")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x51, 0x3f, 0x4f, 0xfb, 0x30,
	0x10, 0x95, 0x9d, 0xa6, 0xfd, 0xf5, 0xf2, 0x23, 0x54, 0x1e, 0x2a, 0x8b, 0xc9, 0x0a, 0x8b, 0x07,
	0xc8, 0x10, 0x16, 0xc4, 0x82, 0x90, 0xc2, 0x90, 0x89, 0xc8, 0xfd, 0xb3, 0x87, 0xc6, 0x42, 0x16,
	0x34, 0x8e, 0x1c, 0x53, 0x29, 0x5f, 0x84, 0xcf, 0x8b, 0x62, 0x9c, 0x8a, 0x32, 0x30, 0xb1, 0xbd,
	0xbb, 0x7b, 0xf7, 0xde, 0xf3, 0x19, 0x62, 0x55, 0xcb, 0xc6, 0x2a, 0xdb, 0xa7, 0xad, 0xd1, 0x56,
	0x93, 0xf0, 0xc5, 0xb4, 0xbb, 0x3a, 0xd9, 0xc2, 0x22, 0xd7, 0x7b, 0xd5, 0x28, 0xdd, 0x14, 0x9e,
	0x40, 0x38, 0xcc, 0x1e, 0xea, 0xda, 0xc8, 0xae, 0xa3, 0x88, 0x21, 0x1e, 0x65, 0x71, 0xea, 0xc8,
	0xa9, 0xef, 0x8a, 0x71, 0x4c, 0x28, 0xcc, 0xb6, 0xd2, 0x74, 0x4a, 0x37, 0x14, 0x33, 0xc4, 0xe7,
	0x62, 0x2c, 0x93, 0x0f, 0x0c, 0x71, 0xae, 0xf7, 0x95, 0xfa, 0x53, 0x59, 0x42, 0x60, 0xb2, 0xd9,
	0x14, 0x39, 0x0d, 0x5c, 0xdb, 0x61, 0xb2, 0x84, 0xe9, 0xda, 0x54, 0xca, 0x76, 0x74, 0xc2, 0x02,
	0x3e, 0x17, 0xbe, 0x22, 0xf7, 0xf0, 0x6f, 0x25, 0xcd, 0x41, 0xed, 0x64, 0x47, 0x43, 0x16, 0xf0,
	0x28, 0xbb, 0xf4, 0x86, 0xa7, 0xc1, 0xd2, 0x91, 0xf5, 0xd8, 0x58, 0xd3, 0x8b, 0xe3, 0xd2, 0xc5,
	0x0a, 0xce, 0x4e, 0x46, 0x64, 0x01, 0xc1, 0xab, 0xec, 0x5d, 0xfa, 0xb9, 0x18, 0x20, 0xb9, 0x82,
	0xf0, 0x50, 0xbd, 0xbd, 0x4b, 0x97, 0x33, 0xca, 0x96, 0xde, 0xc0, 0xaf, 0x8d, 0x0e, 0xe2, 0x8b,
	0x74, 0x87, 0x6f, 0x51, 0xf2, 0x04, 0xe7, 0x3f, 0xa6, 0xc3, 0xa3, 0xd6, 0x7d, 0x2b, 0xbd, 0xae,
	0xc3, 0xdf, 0x8f, 0x85, 0x7f, 0x3d, 0x56, 0x72, 0x7d, 0x64, 0x92, 0x18, 0x70, 0x51, 0xd2, 0x90,
	0x21, 0xfe, 0x5f, 0xe0, 0xa2, 0x1c, 0x84, 0x4b, 0x6d, 0x2c, 0x9d, 0x32, 0xc4, 0x43, 0xe1, 0xf0,
	0xf3, 0xd4, 0x7d, 0xff, 0xcd, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xea, 0x91, 0x19, 0x25, 0x10,
	0x02, 0x00, 0x00,
}
