// Code generated by protoc-gen-go. DO NOT EDIT.
// source: legion.proto

package grpclegion

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// IdentityListRequest contains the clients identity
type IdentityListRequest struct {
	// Identity is the name of the Legion which the client belongs to
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// Legion is a list of all legionnairs known to the client
	IdentityList         []*Identity `protobuf:"bytes,2,rep,name=IdentityList,proto3" json:"IdentityList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdentityListRequest) Reset()         { *m = IdentityListRequest{} }
func (m *IdentityListRequest) String() string { return proto.CompactTextString(m) }
func (*IdentityListRequest) ProtoMessage()    {}
func (*IdentityListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a947f7547cc87c3, []int{0}
}

func (m *IdentityListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityListRequest.Unmarshal(m, b)
}
func (m *IdentityListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityListRequest.Marshal(b, m, deterministic)
}
func (m *IdentityListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityListRequest.Merge(m, src)
}
func (m *IdentityListRequest) XXX_Size() int {
	return xxx_messageInfo_IdentityListRequest.Size(m)
}
func (m *IdentityListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityListRequest proto.InternalMessageInfo

func (m *IdentityListRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *IdentityListRequest) GetIdentityList() []*Identity {
	if m != nil {
		return m.IdentityList
	}
	return nil
}

// IdentityListReply contains a list of legionnaires the server knows
type IdentityListReply struct {
	// Identity is the name of the Legion which the server belongs to
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// IdentityList is a list of all legionnairs known to the server
	IdentityList         []*Identity `protobuf:"bytes,2,rep,name=IdentityList,proto3" json:"IdentityList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IdentityListReply) Reset()         { *m = IdentityListReply{} }
func (m *IdentityListReply) String() string { return proto.CompactTextString(m) }
func (*IdentityListReply) ProtoMessage()    {}
func (*IdentityListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a947f7547cc87c3, []int{1}
}

func (m *IdentityListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdentityListReply.Unmarshal(m, b)
}
func (m *IdentityListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdentityListReply.Marshal(b, m, deterministic)
}
func (m *IdentityListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdentityListReply.Merge(m, src)
}
func (m *IdentityListReply) XXX_Size() int {
	return xxx_messageInfo_IdentityListReply.Size(m)
}
func (m *IdentityListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_IdentityListReply.DiscardUnknown(m)
}

var xxx_messageInfo_IdentityListReply proto.InternalMessageInfo

func (m *IdentityListReply) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *IdentityListReply) GetIdentityList() []*Identity {
	if m != nil {
		return m.IdentityList
	}
	return nil
}

// Identity is the  info for a member of a legion
type Identity struct {
	// UUID is a Unique Identifier for the Identity
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Version is the time of the last heard communication (UnixNano)
	Version string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	// Services is the list of services an Identity currently offers
	Services []*Service `protobuf:"bytes,3,rep,name=Services,proto3" json:"Services,omitempty"`
	// LastContact is the time of the last heard communication (UnixNano)
	LastContact int64 `protobuf:"varint,4,opt,name=LastContact,proto3" json:"LastContact,omitempty"`
	// Port is the port which the Identity was last known to belong communicate over
	Port int32 `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
	// IP is the IP address which the Identity was last known to communicate over
	IP                   []byte   `protobuf:"bytes,6,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a947f7547cc87c3, []int{2}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Identity) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Identity) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Identity) GetLastContact() int64 {
	if m != nil {
		return m.LastContact
	}
	return 0
}

func (m *Identity) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Identity) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

type Service struct {
	// Name is the name of the service
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Port is the port which the service is availible at
	Port                 int32    `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a947f7547cc87c3, []int{3}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*IdentityListRequest)(nil), "grpclegion.IdentityListRequest")
	proto.RegisterType((*IdentityListReply)(nil), "grpclegion.IdentityListReply")
	proto.RegisterType((*Identity)(nil), "grpclegion.Identity")
	proto.RegisterType((*Service)(nil), "grpclegion.Service")
}

func init() { proto.RegisterFile("legion.proto", fileDescriptor_9a947f7547cc87c3) }

var fileDescriptor_9a947f7547cc87c3 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0xfc, 0x6d, 0xd2, 0xa6, 0xfd, 0xbd, 0x06, 0xa1, 0xaf, 0x1e, 0x16, 0x41, 0x5c, 0x72, 0xca,
	0x29, 0x6a, 0xbd, 0x78, 0xd7, 0x4b, 0x20, 0x48, 0xd8, 0x12, 0xaf, 0x12, 0xe3, 0x52, 0x03, 0x31,
	0x1b, 0x37, 0xab, 0x90, 0x93, 0xf8, 0x89, 0xfc, 0x8a, 0x92, 0xb5, 0xf9, 0x53, 0xb0, 0x57, 0x6f,
	0xb3, 0xb3, 0xf3, 0x66, 0x86, 0xc7, 0x03, 0xb7, 0x10, 0xdb, 0x5c, 0x96, 0x41, 0xa5, 0xa4, 0x96,
	0x08, 0x5b, 0x55, 0x65, 0x3f, 0x8c, 0xf7, 0x49, 0x60, 0x15, 0x3e, 0x89, 0x52, 0xe7, 0xba, 0x89,
	0xf2, 0x5a, 0x73, 0xf1, 0xfa, 0x26, 0x6a, 0x8d, 0x17, 0x30, 0xef, 0x68, 0x4a, 0x18, 0xf1, 0x17,
	0xeb, 0xe3, 0x60, 0x18, 0x0b, 0xba, 0x3f, 0xde, 0xab, 0xf0, 0x1a, 0xdc, 0xb1, 0x11, 0xb5, 0x98,
	0x7d, 0x70, 0x6a, 0x4f, 0xe9, 0x7d, 0xc0, 0x72, 0xbf, 0x42, 0x55, 0x34, 0x7f, 0x5a, 0xe0, 0x8b,
	0x0c, 0x61, 0x88, 0x30, 0x49, 0x92, 0xf0, 0xd6, 0x84, 0xfe, 0xe7, 0x06, 0x23, 0x85, 0xd9, 0xbd,
	0x50, 0x75, 0x2e, 0x4b, 0x6a, 0x19, 0xba, 0x7b, 0xe2, 0x39, 0xcc, 0x37, 0x42, 0xbd, 0xe7, 0x99,
	0xa8, 0xa9, 0x6d, 0x02, 0x57, 0xe3, 0xc0, 0xdd, 0x1f, 0xef, 0x45, 0xc8, 0x60, 0x11, 0xa5, 0xb5,
	0xbe, 0x91, 0xa5, 0x4e, 0x33, 0x4d, 0x27, 0x8c, 0xf8, 0x36, 0x1f, 0x53, 0x6d, 0x81, 0x58, 0x2a,
	0x4d, 0xa7, 0x8c, 0xf8, 0x53, 0x6e, 0x30, 0x1e, 0x81, 0x15, 0xc6, 0xd4, 0x61, 0xc4, 0x77, 0xb9,
	0x15, 0xc6, 0xde, 0x25, 0xcc, 0x76, 0x8e, 0xad, 0xfc, 0x2e, 0x7d, 0x11, 0x5d, 0xdf, 0x16, 0xf7,
	0x16, 0xd6, 0x60, 0xb1, 0x7e, 0x00, 0x27, 0x32, 0xa5, 0x30, 0x81, 0xe5, 0xe6, 0x39, 0x55, 0x62,
	0xbc, 0x03, 0x3c, 0xfb, 0x6d, 0x4f, 0xa3, 0x8b, 0x38, 0x39, 0x3d, 0x2c, 0xa8, 0x8a, 0xc6, 0xfb,
	0xf7, 0xe8, 0x98, 0xeb, 0xba, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x62, 0x30, 0x97, 0x6d,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LegionClient is the client API for Legion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LegionClient interface {
	// ShareIdentityList Requests the IdentityList which the server is aware of
	ShareIdentityList(ctx context.Context, in *IdentityListRequest, opts ...grpc.CallOption) (*IdentityListReply, error)
}

type legionClient struct {
	cc *grpc.ClientConn
}

func NewLegionClient(cc *grpc.ClientConn) LegionClient {
	return &legionClient{cc}
}

func (c *legionClient) ShareIdentityList(ctx context.Context, in *IdentityListRequest, opts ...grpc.CallOption) (*IdentityListReply, error) {
	out := new(IdentityListReply)
	err := c.cc.Invoke(ctx, "/grpclegion.Legion/ShareIdentityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LegionServer is the server API for Legion service.
type LegionServer interface {
	// ShareIdentityList Requests the IdentityList which the server is aware of
	ShareIdentityList(context.Context, *IdentityListRequest) (*IdentityListReply, error)
}

func RegisterLegionServer(s *grpc.Server, srv LegionServer) {
	s.RegisterService(&_Legion_serviceDesc, srv)
}

func _Legion_ShareIdentityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LegionServer).ShareIdentityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpclegion.Legion/ShareIdentityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LegionServer).ShareIdentityList(ctx, req.(*IdentityListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Legion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpclegion.Legion",
	HandlerType: (*LegionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareIdentityList",
			Handler:    _Legion_ShareIdentityList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "legion.proto",
}
