// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objects.proto

package grpcdomain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Identity represents a domain
type Identity struct {
	// UUID is a Unique Identifier for the domain
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Version is the version of code being run by the domain
	Version string `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	// Services is the list of services an Identity currently offers
	Services []*ServiceIdentity `protobuf:"bytes,3,rep,name=Services,proto3" json:"Services,omitempty"`
	// LastContact is the time of the last heard communication (UnixNano)
	LastContact int64 `protobuf:"varint,4,opt,name=LastContact,proto3" json:"LastContact,omitempty"`
	// IP is the IP address which the domain was last known to communicate over
	IP []byte `protobuf:"bytes,5,opt,name=IP,proto3" json:"IP,omitempty"`
	// Port is the port which the domain was last known to belong communicate over
	Port                 int32    `protobuf:"varint,6,opt,name=Port,proto3" json:"Port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Identity) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Identity) GetServices() []*ServiceIdentity {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Identity) GetLastContact() int64 {
	if m != nil {
		return m.LastContact
	}
	return 0
}

func (m *Identity) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *Identity) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

// Service represents a service running under a domain
type ServiceIdentity struct {
	// Name is the name of the service
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Port is the port which the service is availible at
	Port int32 `protobuf:"varint,2,opt,name=Port,proto3" json:"Port,omitempty"`
	// LastContact is the time of the last heard communication (UnixNano)
	LastContact          int64    `protobuf:"varint,3,opt,name=LastContact,proto3" json:"LastContact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceIdentity) Reset()         { *m = ServiceIdentity{} }
func (m *ServiceIdentity) String() string { return proto.CompactTextString(m) }
func (*ServiceIdentity) ProtoMessage()    {}
func (*ServiceIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da965bc36916fc1, []int{1}
}

func (m *ServiceIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceIdentity.Unmarshal(m, b)
}
func (m *ServiceIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceIdentity.Marshal(b, m, deterministic)
}
func (m *ServiceIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceIdentity.Merge(m, src)
}
func (m *ServiceIdentity) XXX_Size() int {
	return xxx_messageInfo_ServiceIdentity.Size(m)
}
func (m *ServiceIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceIdentity proto.InternalMessageInfo

func (m *ServiceIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceIdentity) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceIdentity) GetLastContact() int64 {
	if m != nil {
		return m.LastContact
	}
	return 0
}

func init() {
	proto.RegisterType((*Identity)(nil), "grpcdomain.Identity")
	proto.RegisterType((*ServiceIdentity)(nil), "grpcdomain.ServiceIdentity")
}

func init() { proto.RegisterFile("objects.proto", fileDescriptor_7da965bc36916fc1) }

var fileDescriptor_7da965bc36916fc1 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4f, 0xca, 0x4a,
	0x4d, 0x2e, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x2f, 0x2a, 0x48, 0x4e,
	0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x53, 0xda, 0xce, 0xc8, 0xc5, 0xe1, 0x99, 0x92, 0x9a, 0x57, 0x92,
	0x59, 0x52, 0x29, 0x24, 0xc4, 0xc5, 0x12, 0x1a, 0xea, 0xe9, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0x66, 0x0b, 0x49, 0x70, 0xb1, 0x87, 0xa5, 0x16, 0x15, 0x67, 0xe6, 0xe7, 0x49, 0x30,
	0x81, 0x85, 0x61, 0x5c, 0x21, 0x73, 0x2e, 0x8e, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0xd4, 0x62,
	0x09, 0x66, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x69, 0x3d, 0x84, 0xc9, 0x7a, 0x50, 0x39, 0x98, 0xe1,
	0x41, 0x70, 0xc5, 0x42, 0x0a, 0x5c, 0xdc, 0x3e, 0x89, 0xc5, 0x25, 0xce, 0xf9, 0x79, 0x25, 0x89,
	0xc9, 0x25, 0x12, 0x2c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0xc8, 0x42, 0x42, 0x7c, 0x5c, 0x4c, 0x9e,
	0x01, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x4c, 0x9e, 0x01, 0x20, 0x87, 0x05, 0xe4, 0x17,
	0x95, 0x48, 0xb0, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x4a, 0xd1, 0x5c, 0xfc, 0x68, 0x56,
	0x80, 0x94, 0xf9, 0x25, 0xe6, 0xa6, 0xc2, 0xdc, 0x0f, 0x62, 0xc3, 0xb5, 0x32, 0x21, 0xb4, 0xa2,
	0x3b, 0x80, 0x19, 0xc3, 0x01, 0x49, 0x6c, 0xe0, 0x90, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x70, 0xce, 0x74, 0xc3, 0x3a, 0x01, 0x00, 0x00,
}
