// Code generated by protoc-gen-go. DO NOT EDIT.
// source: open_position.proto

package grpcdomain

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// OpenPositionRequest contains the name of the new open position
type OpenPositionRequest struct {
	// Identity is the identity of the client
	Identity *Identity `protobuf:"bytes,1,opt,name=Identity,proto3" json:"Identity,omitempty"`
	// Name is the name of the service which is open
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenPositionRequest) Reset()         { *m = OpenPositionRequest{} }
func (m *OpenPositionRequest) String() string { return proto.CompactTextString(m) }
func (*OpenPositionRequest) ProtoMessage()    {}
func (*OpenPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13daf893ec30de2, []int{0}
}

func (m *OpenPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenPositionRequest.Unmarshal(m, b)
}
func (m *OpenPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenPositionRequest.Marshal(b, m, deterministic)
}
func (m *OpenPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPositionRequest.Merge(m, src)
}
func (m *OpenPositionRequest) XXX_Size() int {
	return xxx_messageInfo_OpenPositionRequest.Size(m)
}
func (m *OpenPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPositionRequest proto.InternalMessageInfo

func (m *OpenPositionRequest) GetIdentity() *Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *OpenPositionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// OpenPositionReply contains the consent and proficiency of the servir
type OpenPositionReply struct {
	// Accept is whether or not the domain is willing to take the position
	Accept bool `protobuf:"varint,1,opt,name=Accept,proto3" json:"Accept,omitempty"`
	// Proficiency is the measure of the servers effectiveness of performing the task
	Proficiency          int32    `protobuf:"varint,2,opt,name=Proficiency,proto3" json:"Proficiency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenPositionReply) Reset()         { *m = OpenPositionReply{} }
func (m *OpenPositionReply) String() string { return proto.CompactTextString(m) }
func (*OpenPositionReply) ProtoMessage()    {}
func (*OpenPositionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f13daf893ec30de2, []int{1}
}

func (m *OpenPositionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenPositionReply.Unmarshal(m, b)
}
func (m *OpenPositionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenPositionReply.Marshal(b, m, deterministic)
}
func (m *OpenPositionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPositionReply.Merge(m, src)
}
func (m *OpenPositionReply) XXX_Size() int {
	return xxx_messageInfo_OpenPositionReply.Size(m)
}
func (m *OpenPositionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPositionReply.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPositionReply proto.InternalMessageInfo

func (m *OpenPositionReply) GetAccept() bool {
	if m != nil {
		return m.Accept
	}
	return false
}

func (m *OpenPositionReply) GetProficiency() int32 {
	if m != nil {
		return m.Proficiency
	}
	return 0
}

func init() {
	proto.RegisterType((*OpenPositionRequest)(nil), "grpcdomain.OpenPositionRequest")
	proto.RegisterType((*OpenPositionReply)(nil), "grpcdomain.OpenPositionReply")
}

func init() { proto.RegisterFile("open_position.proto", fileDescriptor_f13daf893ec30de2) }

var fileDescriptor_f13daf893ec30de2 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0x2f, 0x48, 0xcd,
	0x8b, 0x2f, 0xc8, 0x2f, 0xce, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x4a, 0x2f, 0x2a, 0x48, 0x4e, 0xc9, 0xcf, 0x4d, 0xcc, 0xcc, 0x93, 0xe2, 0xcd, 0x4f, 0xca,
	0x4a, 0x4d, 0x2e, 0x29, 0x86, 0x48, 0x29, 0x45, 0x73, 0x09, 0xfb, 0x17, 0xa4, 0xe6, 0x05, 0x40,
	0x35, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x19, 0x70, 0x71, 0x78, 0xa6, 0xa4, 0xe6,
	0x95, 0x64, 0x96, 0x54, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x21, 0x0c, 0xd1,
	0x83, 0xc9, 0x05, 0xc1, 0x55, 0x09, 0x09, 0x71, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29,
	0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0xbe, 0x5c, 0x82, 0xa8, 0x86, 0x17, 0xe4, 0x54, 0x0a,
	0x89, 0x71, 0xb1, 0x39, 0x26, 0x27, 0xa7, 0x16, 0x94, 0x80, 0x0d, 0xe6, 0x08, 0x82, 0xf2, 0x84,
	0x14, 0xb8, 0xb8, 0x03, 0x8a, 0xf2, 0xd3, 0x32, 0x93, 0x33, 0x53, 0xf3, 0x92, 0x2b, 0xc1, 0xe6,
	0xb0, 0x06, 0x21, 0x0b, 0x25, 0xb1, 0x81, 0x9d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x68,
	0xc0, 0xb2, 0x0f, 0xe4, 0x00, 0x00, 0x00,
}
