// Code generated by protoc-gen-go. DO NOT EDIT.
// source: light_orchastrator.proto

package grpcdomain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// SubscribeLightsRequest contains the identifying information from the subscriber
type SubscribeLightsRequest struct {
	// Type is the Type of the Subscriber
	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	// UUID is a Unique Identifier for the Subscriber
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeLightsRequest) Reset()         { *m = SubscribeLightsRequest{} }
func (m *SubscribeLightsRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeLightsRequest) ProtoMessage()    {}
func (*SubscribeLightsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{0}
}

func (m *SubscribeLightsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeLightsRequest.Unmarshal(m, b)
}
func (m *SubscribeLightsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeLightsRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeLightsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeLightsRequest.Merge(m, src)
}
func (m *SubscribeLightsRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeLightsRequest.Size(m)
}
func (m *SubscribeLightsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeLightsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeLightsRequest proto.InternalMessageInfo

func (m *SubscribeLightsRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SubscribeLightsRequest) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

// SubscribeLightsReply contains the time and series of RGBA colors which should be displayed
type SubscribeLightsReply struct {
	// DisplayTime is the time which the lights should be applied
	DisplayTime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=DisplayTime,proto3" json:"DisplayTime,omitempty"`
	// Colors are the series of colors which should be displayed
	Colors               []uint32 `protobuf:"varint,2,rep,packed,name=Colors,proto3" json:"Colors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeLightsReply) Reset()         { *m = SubscribeLightsReply{} }
func (m *SubscribeLightsReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeLightsReply) ProtoMessage()    {}
func (*SubscribeLightsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{1}
}

func (m *SubscribeLightsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeLightsReply.Unmarshal(m, b)
}
func (m *SubscribeLightsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeLightsReply.Marshal(b, m, deterministic)
}
func (m *SubscribeLightsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeLightsReply.Merge(m, src)
}
func (m *SubscribeLightsReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeLightsReply.Size(m)
}
func (m *SubscribeLightsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeLightsReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeLightsReply proto.InternalMessageInfo

func (m *SubscribeLightsReply) GetDisplayTime() *timestamp.Timestamp {
	if m != nil {
		return m.DisplayTime
	}
	return nil
}

func (m *SubscribeLightsReply) GetColors() []uint32 {
	if m != nil {
		return m.Colors
	}
	return nil
}

// GetDevicesReply contains the DeviceNode hierarchy and all subscribed devices
type GetDevicesReply struct {
	// DeviceNodeTree is DeviceNode hierarchy
	DeviceNodeTree *DeviceNode `protobuf:"bytes,1,opt,name=DeviceNodeTree,proto3" json:"DeviceNodeTree,omitempty"`
	// Devices is the list of subscribed devices
	Devices              []*Device `protobuf:"bytes,2,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDevicesReply) Reset()         { *m = GetDevicesReply{} }
func (m *GetDevicesReply) String() string { return proto.CompactTextString(m) }
func (*GetDevicesReply) ProtoMessage()    {}
func (*GetDevicesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{2}
}

func (m *GetDevicesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesReply.Unmarshal(m, b)
}
func (m *GetDevicesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesReply.Marshal(b, m, deterministic)
}
func (m *GetDevicesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesReply.Merge(m, src)
}
func (m *GetDevicesReply) XXX_Size() int {
	return xxx_messageInfo_GetDevicesReply.Size(m)
}
func (m *GetDevicesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesReply proto.InternalMessageInfo

func (m *GetDevicesReply) GetDeviceNodeTree() *DeviceNode {
	if m != nil {
		return m.DeviceNodeTree
	}
	return nil
}

func (m *GetDevicesReply) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

// MoveDeviceRequest contains the new position and orientation
type MoveDeviceRequest struct {
	// Device contians the UUID and type of the device to help find the device to move
	// the Location and Orientation are where the device should be moved to
	Device               *Device  `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDeviceRequest) Reset()         { *m = MoveDeviceRequest{} }
func (m *MoveDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*MoveDeviceRequest) ProtoMessage()    {}
func (*MoveDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{3}
}

func (m *MoveDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDeviceRequest.Unmarshal(m, b)
}
func (m *MoveDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDeviceRequest.Marshal(b, m, deterministic)
}
func (m *MoveDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDeviceRequest.Merge(m, src)
}
func (m *MoveDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_MoveDeviceRequest.Size(m)
}
func (m *MoveDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDeviceRequest proto.InternalMessageInfo

func (m *MoveDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

// InsertDeviceInHierarchyRequest contains the UUID of the parent and ne child
type InsertDeviceInHierarchyRequest struct {
	// ParentUUID is the UUID of the parent for the new child
	ParentUUID string `protobuf:"bytes,1,opt,name=ParentUUID,proto3" json:"ParentUUID,omitempty"`
	// ChildUUID is the UUID of the new child
	ChildUUID            string   `protobuf:"bytes,2,opt,name=ChildUUID,proto3" json:"ChildUUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertDeviceInHierarchyRequest) Reset()         { *m = InsertDeviceInHierarchyRequest{} }
func (m *InsertDeviceInHierarchyRequest) String() string { return proto.CompactTextString(m) }
func (*InsertDeviceInHierarchyRequest) ProtoMessage()    {}
func (*InsertDeviceInHierarchyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{4}
}

func (m *InsertDeviceInHierarchyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertDeviceInHierarchyRequest.Unmarshal(m, b)
}
func (m *InsertDeviceInHierarchyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertDeviceInHierarchyRequest.Marshal(b, m, deterministic)
}
func (m *InsertDeviceInHierarchyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertDeviceInHierarchyRequest.Merge(m, src)
}
func (m *InsertDeviceInHierarchyRequest) XXX_Size() int {
	return xxx_messageInfo_InsertDeviceInHierarchyRequest.Size(m)
}
func (m *InsertDeviceInHierarchyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertDeviceInHierarchyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertDeviceInHierarchyRequest proto.InternalMessageInfo

func (m *InsertDeviceInHierarchyRequest) GetParentUUID() string {
	if m != nil {
		return m.ParentUUID
	}
	return ""
}

func (m *InsertDeviceInHierarchyRequest) GetChildUUID() string {
	if m != nil {
		return m.ChildUUID
	}
	return ""
}

// DeviceNode represents a DeviceNode in the DeviceNode hierarchy
type DeviceNode struct {
	// UUID is the UUID of the DeviceNode
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Type is the Type of the DeviceNode
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	// Children are the Children of the DeviceNode
	Children             []*DeviceNode `protobuf:"bytes,3,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeviceNode) Reset()         { *m = DeviceNode{} }
func (m *DeviceNode) String() string { return proto.CompactTextString(m) }
func (*DeviceNode) ProtoMessage()    {}
func (*DeviceNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{5}
}

func (m *DeviceNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceNode.Unmarshal(m, b)
}
func (m *DeviceNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceNode.Marshal(b, m, deterministic)
}
func (m *DeviceNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceNode.Merge(m, src)
}
func (m *DeviceNode) XXX_Size() int {
	return xxx_messageInfo_DeviceNode.Size(m)
}
func (m *DeviceNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceNode.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceNode proto.InternalMessageInfo

func (m *DeviceNode) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *DeviceNode) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DeviceNode) GetChildren() []*DeviceNode {
	if m != nil {
		return m.Children
	}
	return nil
}

// Device represents a subscriber in the list of subscribers
type Device struct {
	// UUID is the UUID of the Device
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// Type is the Type of the Device
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	// Location is the Location of the Device
	Location *Vector `protobuf:"bytes,3,opt,name=Location,proto3" json:"Location,omitempty"`
	// Orientation is the Orientation of the Device
	Orientation          *Orientation `protobuf:"bytes,4,opt,name=Orientation,proto3" json:"Orientation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{6}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Device) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Device) GetLocation() *Vector {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Device) GetOrientation() *Orientation {
	if m != nil {
		return m.Orientation
	}
	return nil
}

// Orientation represents a direction in 3D space
type Orientation struct {
	// Theta is the horizontal rotation in radians [0,2pi)
	Theta float32 `protobuf:"fixed32,1,opt,name=Theta,proto3" json:"Theta,omitempty"`
	// Theta is the vertical rotation in radians [pi/2,pi/2]
	Phi                  float32  `protobuf:"fixed32,2,opt,name=Phi,proto3" json:"Phi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Orientation) Reset()         { *m = Orientation{} }
func (m *Orientation) String() string { return proto.CompactTextString(m) }
func (*Orientation) ProtoMessage()    {}
func (*Orientation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{7}
}

func (m *Orientation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orientation.Unmarshal(m, b)
}
func (m *Orientation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orientation.Marshal(b, m, deterministic)
}
func (m *Orientation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orientation.Merge(m, src)
}
func (m *Orientation) XXX_Size() int {
	return xxx_messageInfo_Orientation.Size(m)
}
func (m *Orientation) XXX_DiscardUnknown() {
	xxx_messageInfo_Orientation.DiscardUnknown(m)
}

var xxx_messageInfo_Orientation proto.InternalMessageInfo

func (m *Orientation) GetTheta() float32 {
	if m != nil {
		return m.Theta
	}
	return 0
}

func (m *Orientation) GetPhi() float32 {
	if m != nil {
		return m.Phi
	}
	return 0
}

// Vector represents a location in 3D space
type Vector struct {
	// Theta is the X cooridnate in meters
	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	// Theta is the Y cooridnate in meters
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	// Theta is the Z cooridnate in meters
	Z                    float32  `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{8}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Vector) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

// Empty is empty, Duh.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0a167111198e4c0, []int{9}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SubscribeLightsRequest)(nil), "grpcdomain.SubscribeLightsRequest")
	proto.RegisterType((*SubscribeLightsReply)(nil), "grpcdomain.SubscribeLightsReply")
	proto.RegisterType((*GetDevicesReply)(nil), "grpcdomain.GetDevicesReply")
	proto.RegisterType((*MoveDeviceRequest)(nil), "grpcdomain.MoveDeviceRequest")
	proto.RegisterType((*InsertDeviceInHierarchyRequest)(nil), "grpcdomain.InsertDeviceInHierarchyRequest")
	proto.RegisterType((*DeviceNode)(nil), "grpcdomain.DeviceNode")
	proto.RegisterType((*Device)(nil), "grpcdomain.Device")
	proto.RegisterType((*Orientation)(nil), "grpcdomain.Orientation")
	proto.RegisterType((*Vector)(nil), "grpcdomain.Vector")
	proto.RegisterType((*Empty)(nil), "grpcdomain.Empty")
}

func init() { proto.RegisterFile("light_orchastrator.proto", fileDescriptor_d0a167111198e4c0) }

var fileDescriptor_d0a167111198e4c0 = []byte{
	// 553 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xad, 0x9d, 0x36, 0x6d, 0x27, 0xdf, 0x47, 0xe9, 0xa8, 0x4a, 0xa3, 0x00, 0x25, 0xda, 0xab,
	0xaa, 0x42, 0x2e, 0x0a, 0xe2, 0x02, 0x09, 0x95, 0x4a, 0x0d, 0x82, 0x48, 0x85, 0x56, 0x4b, 0x8a,
	0xda, 0x20, 0x81, 0x1c, 0x67, 0x89, 0x57, 0x72, 0xbc, 0x66, 0xbd, 0xa9, 0xe4, 0x2b, 0x1e, 0x84,
	0x87, 0xe2, 0x95, 0x90, 0xd7, 0xeb, 0x78, 0x49, 0xd2, 0x8a, 0xbb, 0x9d, 0xf1, 0x99, 0x33, 0xbf,
	0xc7, 0xd0, 0x8a, 0xf8, 0x24, 0x54, 0xdf, 0x84, 0x0c, 0x42, 0x3f, 0x55, 0xd2, 0x57, 0x42, 0x7a,
	0x89, 0x14, 0x4a, 0x20, 0x4c, 0x64, 0x12, 0x8c, 0xc5, 0xd4, 0xe7, 0x71, 0xfb, 0xe9, 0x44, 0x88,
	0x49, 0xc4, 0x8e, 0xf5, 0x97, 0xd1, 0xec, 0xfb, 0xb1, 0xe2, 0x53, 0x96, 0x2a, 0x7f, 0x9a, 0x14,
	0x60, 0x72, 0x0a, 0xcd, 0x4f, 0xb3, 0x51, 0x1a, 0x48, 0x3e, 0x62, 0xe7, 0x39, 0x63, 0x4a, 0xd9,
	0x8f, 0x19, 0x4b, 0x15, 0x22, 0xac, 0x0f, 0xb2, 0x84, 0xb5, 0x9c, 0x8e, 0x73, 0xb8, 0x4d, 0xf5,
	0x3b, 0xf7, 0x5d, 0x5d, 0xf5, 0x7b, 0x2d, 0xb7, 0xf0, 0xe5, 0x6f, 0x12, 0xc1, 0xde, 0x12, 0x43,
	0x12, 0x65, 0xf8, 0x1a, 0x1a, 0x3d, 0x9e, 0x26, 0x91, 0x9f, 0x0d, 0xf8, 0xb4, 0xa0, 0x69, 0x74,
	0xdb, 0x5e, 0x51, 0x90, 0x57, 0x16, 0xe4, 0x0d, 0xca, 0x82, 0xa8, 0x0d, 0xc7, 0x26, 0xd4, 0xcf,
	0x44, 0x24, 0x64, 0xda, 0x72, 0x3b, 0xb5, 0xc3, 0xff, 0xa9, 0xb1, 0xc8, 0x4f, 0xd8, 0x79, 0xc7,
	0x54, 0x8f, 0xdd, 0xf2, 0x80, 0x99, 0x44, 0x27, 0xf0, 0xa0, 0xb0, 0x3f, 0x8a, 0x31, 0x1b, 0x48,
	0x56, 0xe6, 0x6a, 0x7a, 0xd5, 0x20, 0xbc, 0x0a, 0x41, 0x17, 0xd0, 0xf8, 0x0c, 0x36, 0x0d, 0x9f,
	0xce, 0xd5, 0xe8, 0xe2, 0x72, 0x20, 0x2d, 0x21, 0xe4, 0x0d, 0xec, 0x7e, 0x10, 0xb7, 0xcc, 0xb8,
	0xcd, 0xac, 0x8e, 0xa0, 0x5e, 0x38, 0x4c, 0xea, 0x55, 0x0c, 0x06, 0x41, 0xbe, 0xc2, 0x41, 0x3f,
	0x4e, 0x99, 0x34, 0x4d, 0xf4, 0xe3, 0xf7, 0x9c, 0x49, 0x5f, 0x06, 0x61, 0x56, 0xb2, 0x1d, 0x00,
	0x5c, 0xfa, 0x92, 0xc5, 0x4a, 0xcf, 0xba, 0x98, 0xbf, 0xe5, 0xc1, 0xc7, 0xb0, 0x7d, 0x16, 0xf2,
	0x68, 0x6c, 0xad, 0xa2, 0x72, 0x90, 0x10, 0xa0, 0x6a, 0x70, 0xbe, 0x31, 0xa7, 0xda, 0xd8, 0x7c,
	0xb3, 0xae, 0xb5, 0xd9, 0x2e, 0x6c, 0x69, 0x0a, 0xc9, 0xe2, 0x56, 0x4d, 0x4f, 0xe1, 0xae, 0xf1,
	0xcd, 0x71, 0xe4, 0x97, 0x53, 0xb6, 0xfd, 0xcf, 0x69, 0x3c, 0xd8, 0x3a, 0x17, 0x81, 0xaf, 0xb8,
	0xc8, 0xd3, 0x2c, 0x8d, 0xea, 0x33, 0x0b, 0x94, 0x90, 0x74, 0x8e, 0xc1, 0x57, 0xd0, 0xb8, 0x90,
	0x9c, 0xc5, 0xaa, 0x08, 0x59, 0xd7, 0x21, 0xfb, 0x76, 0x88, 0xf5, 0x99, 0xda, 0x58, 0xf2, 0xf2,
	0xaf, 0x50, 0xdc, 0x83, 0x8d, 0x41, 0xc8, 0x94, 0xaf, 0x4b, 0x74, 0x69, 0x61, 0xe0, 0x43, 0xa8,
	0x5d, 0x86, 0x5c, 0x97, 0xe8, 0xd2, 0xfc, 0x49, 0xba, 0x50, 0x2f, 0xaa, 0xc0, 0xff, 0xc0, 0xb9,
	0x36, 0x68, 0xe7, 0x3a, 0xb7, 0x6e, 0x0c, 0xce, 0xb9, 0xc9, 0xad, 0xa1, 0x6e, 0xc0, 0xa5, 0xce,
	0x90, 0x6c, 0xc2, 0xc6, 0xdb, 0x69, 0xa2, 0xb2, 0xee, 0x6f, 0x17, 0x50, 0x6b, 0xe0, 0x22, 0x97,
	0xa5, 0x34, 0xba, 0xc4, 0x2f, 0xb0, 0xb3, 0x20, 0x11, 0x24, 0x76, 0x0f, 0xab, 0x15, 0xd8, 0xee,
	0xdc, 0x8b, 0x49, 0xa2, 0x8c, 0xac, 0x3d, 0x77, 0xf0, 0x04, 0xa0, 0x52, 0x04, 0xee, 0xda, 0x31,
	0xba, 0xa8, 0xf6, 0x23, 0xdb, 0xb5, 0x20, 0x1e, 0xb2, 0x86, 0xa7, 0x00, 0xd5, 0x41, 0xe3, 0x13,
	0x1b, 0xbc, 0x74, 0xe8, 0xed, 0x65, 0x7a, 0xb2, 0x86, 0x43, 0xd8, 0xbf, 0xe3, 0xa2, 0xf1, 0xc8,
	0xc6, 0xdf, 0x7f, 0xf6, 0x2b, 0xb9, 0x47, 0x75, 0xfd, 0xa3, 0x78, 0xf1, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xd3, 0x19, 0xde, 0xb9, 0xef, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LightOrcharstratorClient is the client API for LightOrcharstrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LightOrcharstratorClient interface {
	// SubscribeLights requests a stream of lights
	SubscribeLights(ctx context.Context, in *SubscribeLightsRequest, opts ...grpc.CallOption) (LightOrcharstrator_SubscribeLightsClient, error)
	// GetDevices returns the DeviceNode hierarchy and all subscribed devices
	GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesReply, error)
	// MoveDevice changes a devices location and orientation
	MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*Empty, error)
	// InsertDeviceInHierarchy inserts a device into the DeviceNode hierarchy
	InsertDeviceInHierarchy(ctx context.Context, in *InsertDeviceInHierarchyRequest, opts ...grpc.CallOption) (*Empty, error)
}

type lightOrcharstratorClient struct {
	cc *grpc.ClientConn
}

func NewLightOrcharstratorClient(cc *grpc.ClientConn) LightOrcharstratorClient {
	return &lightOrcharstratorClient{cc}
}

func (c *lightOrcharstratorClient) SubscribeLights(ctx context.Context, in *SubscribeLightsRequest, opts ...grpc.CallOption) (LightOrcharstrator_SubscribeLightsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LightOrcharstrator_serviceDesc.Streams[0], "/grpcdomain.LightOrcharstrator/SubscribeLights", opts...)
	if err != nil {
		return nil, err
	}
	x := &lightOrcharstratorSubscribeLightsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LightOrcharstrator_SubscribeLightsClient interface {
	Recv() (*SubscribeLightsReply, error)
	grpc.ClientStream
}

type lightOrcharstratorSubscribeLightsClient struct {
	grpc.ClientStream
}

func (x *lightOrcharstratorSubscribeLightsClient) Recv() (*SubscribeLightsReply, error) {
	m := new(SubscribeLightsReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *lightOrcharstratorClient) GetDevices(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetDevicesReply, error) {
	out := new(GetDevicesReply)
	err := c.cc.Invoke(ctx, "/grpcdomain.LightOrcharstrator/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightOrcharstratorClient) MoveDevice(ctx context.Context, in *MoveDeviceRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpcdomain.LightOrcharstrator/MoveDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightOrcharstratorClient) InsertDeviceInHierarchy(ctx context.Context, in *InsertDeviceInHierarchyRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/grpcdomain.LightOrcharstrator/InsertDeviceInHierarchy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightOrcharstratorServer is the server API for LightOrcharstrator service.
type LightOrcharstratorServer interface {
	// SubscribeLights requests a stream of lights
	SubscribeLights(*SubscribeLightsRequest, LightOrcharstrator_SubscribeLightsServer) error
	// GetDevices returns the DeviceNode hierarchy and all subscribed devices
	GetDevices(context.Context, *Empty) (*GetDevicesReply, error)
	// MoveDevice changes a devices location and orientation
	MoveDevice(context.Context, *MoveDeviceRequest) (*Empty, error)
	// InsertDeviceInHierarchy inserts a device into the DeviceNode hierarchy
	InsertDeviceInHierarchy(context.Context, *InsertDeviceInHierarchyRequest) (*Empty, error)
}

// UnimplementedLightOrcharstratorServer can be embedded to have forward compatible implementations.
type UnimplementedLightOrcharstratorServer struct {
}

func (*UnimplementedLightOrcharstratorServer) SubscribeLights(req *SubscribeLightsRequest, srv LightOrcharstrator_SubscribeLightsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeLights not implemented")
}
func (*UnimplementedLightOrcharstratorServer) GetDevices(ctx context.Context, req *Empty) (*GetDevicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevices not implemented")
}
func (*UnimplementedLightOrcharstratorServer) MoveDevice(ctx context.Context, req *MoveDeviceRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveDevice not implemented")
}
func (*UnimplementedLightOrcharstratorServer) InsertDeviceInHierarchy(ctx context.Context, req *InsertDeviceInHierarchyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertDeviceInHierarchy not implemented")
}

func RegisterLightOrcharstratorServer(s *grpc.Server, srv LightOrcharstratorServer) {
	s.RegisterService(&_LightOrcharstrator_serviceDesc, srv)
}

func _LightOrcharstrator_SubscribeLights_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLightsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightOrcharstratorServer).SubscribeLights(m, &lightOrcharstratorSubscribeLightsServer{stream})
}

type LightOrcharstrator_SubscribeLightsServer interface {
	Send(*SubscribeLightsReply) error
	grpc.ServerStream
}

type lightOrcharstratorSubscribeLightsServer struct {
	grpc.ServerStream
}

func (x *lightOrcharstratorSubscribeLightsServer) Send(m *SubscribeLightsReply) error {
	return x.ServerStream.SendMsg(m)
}

func _LightOrcharstrator_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightOrcharstratorServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdomain.LightOrcharstrator/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightOrcharstratorServer).GetDevices(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightOrcharstrator_MoveDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightOrcharstratorServer).MoveDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdomain.LightOrcharstrator/MoveDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightOrcharstratorServer).MoveDevice(ctx, req.(*MoveDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LightOrcharstrator_InsertDeviceInHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertDeviceInHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightOrcharstratorServer).InsertDeviceInHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdomain.LightOrcharstrator/InsertDeviceInHierarchy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightOrcharstratorServer).InsertDeviceInHierarchy(ctx, req.(*InsertDeviceInHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LightOrcharstrator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdomain.LightOrcharstrator",
	HandlerType: (*LightOrcharstratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDevices",
			Handler:    _LightOrcharstrator_GetDevices_Handler,
		},
		{
			MethodName: "MoveDevice",
			Handler:    _LightOrcharstrator_MoveDevice_Handler,
		},
		{
			MethodName: "InsertDeviceInHierarchy",
			Handler:    _LightOrcharstrator_InsertDeviceInHierarchy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeLights",
			Handler:       _LightOrcharstrator_SubscribeLights_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "light_orchastrator.proto",
}
